const js = require("@eslint/js");
const prettier = require("eslint-config-prettier");

module.exports = [
  {
    ignores: ["node_modules/**", "release/**", "tmp/**", "build/**", "dist/**", ".patch-work-*/**"],
  },
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: {
        // Node.js (main process + scripts)
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        module: "readonly",
        require: "readonly",
        exports: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        queueMicrotask: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        AbortController: "readonly",
        setImmediate: "readonly",
        clearImmediate: "readonly",
        structuredClone: "readonly",
        crypto: "readonly",
        // Renderer / settings (browser window globals)
        window: "readonly",
        document: "readonly",
        HTMLElement: "readonly",
        Node: "readonly",
        localStorage: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        fetch: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        matchMedia: "readonly",
        DragEvent: "readonly",
        ClipboardEvent: "readonly",
        InputEvent: "readonly",
        KeyboardEvent: "readonly",
        MouseEvent: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        FileReader: "readonly",
        Blob: "readonly",
        FormData: "readonly",
        DOMParser: "readonly",
        XMLSerializer: "readonly",
        XMLDocument: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLFormElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLDialogElement: "readonly",
        HTMLAnchorElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLSpanElement: "readonly",
        HTMLLabelElement: "readonly",
        HTMLUListElement: "readonly",
        HTMLLIElement: "readonly",
        // Browser CSS/layout APIs used by renderer/settings.
        getComputedStyle: "readonly",
        CSS: "readonly",
        performance: "readonly",
        requestIdleCallback: "readonly",
        cancelIdleCallback: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        Range: "readonly",
        Selection: "readonly",
        ShadowRoot: "readonly",
      },
    },
    rules: {
      // Match existing project style: double quotes, semicolons.
      quotes: ["error", "double", { avoidEscape: true, allowTemplateLiterals: true }],
      semi: ["error", "always"],
      "no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // Allow console.* in a desktop app.
      "no-console": "off",
      // Common in existing code (e.g. switch fallthroughs in providers.js).
      "no-case-declarations": "off",
      // Refresh loops often reassign loop vars.
      "no-await-in-loop": "off",
      // Allow function hoisting in module-scope helpers.
      "no-use-before-define": "off",
    },
  },
  prettier,
];
